[[constraint]]
  name = "github.com/tav/golly"
  branch = "master"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/lucas-clemente/quic-go"
  revision = "7356fc05d5799392e5131b1a8865c00455158c4e"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
